/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/man.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/man.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Hips} />
          <group name="EyeAO_Mesh" />
          <group name="EyeAO_Mesh001" />
          <group name="EyeAO_Mesh146" />
          <group name="Eyelash_Mesh" />
          <group name="Eyelash_Mesh001" />
          <group name="Eyelash_Mesh146" />
          <group name="Head_Mesh" />
          <group name="Head_Mesh001" />
          <group name="Head_Mesh146" />
          <group name="Teeth_Mesh" />
          <group name="Teeth_Mesh001" />
          <group name="Teeth_Mesh146" />
          <group name="Tongue_Mesh" />
          <group name="Tongue_Mesh001" />
          <group name="Tongue_Mesh146" />
          <skinnedMesh name="avaturn_hair_0" geometry={nodes.avaturn_hair_0.geometry} material={materials['avaturn_hair_0_material.146']} skeleton={nodes.avaturn_hair_0.skeleton} />
          <skinnedMesh name="avaturn_hair_1" geometry={nodes.avaturn_hair_1.geometry} material={materials['avaturn_hair_1_material.146']} skeleton={nodes.avaturn_hair_1.skeleton} />
          <skinnedMesh name="avaturn_look_0" geometry={nodes.avaturn_look_0.geometry} material={materials['avaturn_look_0_material.146']} skeleton={nodes.avaturn_look_0.skeleton} />
          <skinnedMesh name="avaturn_shoes_0" geometry={nodes.avaturn_shoes_0.geometry} material={materials['avaturn_shoes_0_material.146']} skeleton={nodes.avaturn_shoes_0.skeleton} />
          <skinnedMesh name="Body_Mesh" geometry={nodes.Body_Mesh.geometry} material={materials['Body.146']} skeleton={nodes.Body_Mesh.skeleton} />
          <skinnedMesh name="Eye_Mesh" geometry={nodes.Eye_Mesh.geometry} material={materials['Eyes.146']} skeleton={nodes.Eye_Mesh.skeleton} morphTargetDictionary={nodes.Eye_Mesh.morphTargetDictionary} morphTargetInfluences={nodes.Eye_Mesh.morphTargetInfluences} />
          <skinnedMesh name="EyeAO_Mesh002" geometry={nodes.EyeAO_Mesh002.geometry} material={materials['EyeAO.146']} skeleton={nodes.EyeAO_Mesh002.skeleton} morphTargetDictionary={nodes.EyeAO_Mesh002.morphTargetDictionary} morphTargetInfluences={nodes.EyeAO_Mesh002.morphTargetInfluences} />
          <skinnedMesh name="Eyelash_Mesh002" geometry={nodes.Eyelash_Mesh002.geometry} material={materials['Eyelash.146']} skeleton={nodes.Eyelash_Mesh002.skeleton} morphTargetDictionary={nodes.Eyelash_Mesh002.morphTargetDictionary} morphTargetInfluences={nodes.Eyelash_Mesh002.morphTargetInfluences} />
          <skinnedMesh name="Head_Mesh002" geometry={nodes.Head_Mesh002.geometry} material={materials['Head.146']} skeleton={nodes.Head_Mesh002.skeleton} morphTargetDictionary={nodes.Head_Mesh002.morphTargetDictionary} morphTargetInfluences={nodes.Head_Mesh002.morphTargetInfluences} />
          <skinnedMesh name="Teeth_Mesh002" geometry={nodes.Teeth_Mesh002.geometry} material={materials['Teeth.292']} skeleton={nodes.Teeth_Mesh002.skeleton} morphTargetDictionary={nodes.Teeth_Mesh002.morphTargetDictionary} morphTargetInfluences={nodes.Teeth_Mesh002.morphTargetInfluences} />
          <skinnedMesh name="Tongue_Mesh002" geometry={nodes.Tongue_Mesh002.geometry} material={materials['Teeth.293']} skeleton={nodes.Tongue_Mesh002.skeleton} morphTargetDictionary={nodes.Tongue_Mesh002.morphTargetDictionary} morphTargetInfluences={nodes.Tongue_Mesh002.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/man.glb')
